### ISSUE TITLE
Make library compatible with older build systems

### ISSUE THREAD

**Issue by afrojezus** [Dintero/email-chk#81]
Currently the library targets `ESNext` and does ~~not~~ currently work when used with an older build system (if said build system can transform arrow functions). It should also support build systems that do not transform newer syntax.

**Comment by frodeaa** [comment]
You can probably have multiple tsconfig files in order to create different artifacts

**Comment by afrojezus** [comment]
Turns out it _does_ work with an older build system and my local machine just had broken packages..

The library should still have compatible modules for various build systems in the future, should be enough with ESM (for targeting newer runtime) and CJS (for targeting older runtime), but not a major concern for now.
